AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LeadingCommentSpace:
  Exclude:
    - '**/*.ru'
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/api_valve/middleware/logging.rb
Metrics/BlockLength:
  Exclude:
    - '**/*.ru'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/api_valve/middleware/logging.rb

Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FetchEnvVar:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
