name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
jobs:
  build_26:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activesupport: ['5.2', '6.0', '6.1']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.6.x
    - name: Bundle
      env:
        ACTIVESUPPORT: ${{ matrix.activesupport }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Rspec
      run: bundle exec rspec
    - name: Rubocop
      run: bundle exec rubocop

  build_26:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activesupport: ['5.2', '6.0', '6.1']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Bundle
      env:
        ACTIVESUPPORT: ${{ matrix.activesupport }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Rspec
      run: bundle exec rspec
    - name: Rubocop
      run: bundle exec rubocop
